# threshold for the canny edge detector (see https://docs.opencv.org/3.2.0/dd/d1a/group__imgproc__feature.html#ga04723e007ed888ddf11d9ba04e2232de)
canny_threshold: 70

# coordinates of the point, which will be backprojected to the camera image from the specified frame
world_frame_id: "down_rgbd/color_optical"
# world_frame_id: "gps_origin"
world_point:
  x: 0.0
  y: 0.0
  z: 0.0
formation_circle:
  radius_threshold: 3.0

memory_size: 20  #how many centroids to store, how fast centroids will be updated
rate:
  publish: 25 # [Hz] how often to publish my topic?
  check_subscribers: 1 # [Hz] how often check whether msgs are arriving?
kalman:
  q: 0.1 
  r: 5.0 